export const data = [
    {
        id: 1,
        img: "assets/p1.jpg",
        title: "Land Registration in Ghana",
        category: "Lands & Properties",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
        posted_by: "Ghana Lands",
    },
    {
        id: 2,
        img: "assets/p2.jpg",
        title: "Land Registration in Ghana",
        category: "Lands & Properties",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
        posted_by: "Ghana Lands",
    },
    {
        id: 3,
        img: "assets/h2.jpg",
        title: "Land Registration in Ghana",
        category: "Lands & Properties",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
        posted_by: "Ghana Lands",
    },
    {
        id: 4,
        img: "assets/p4.jpg",
        title: "Land Registration in Ghana",
        category: "Lands & Properties",
        desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
        posted_by: "Ghana Lands",
    },
    //     {
    //         id:5,
    //         img:"assets/p5.jpg",
    //         title: "Land Registration in Ghana",
    //         category: "Lands & Properties",
    //         desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
    //         posted_by: "Ghana Lands",
    //     },
    //     {
    //         id:6,
    //         img:"assets/h4.jpg",
    //         title: "Land Registration in Ghana",
    //         category: "Lands & Properties",
    //         desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
    //         posted_by: "Ghana Lands",
    //     },
    //     {
    //         id:7,
    //         img:"assets/p7.jpg",
    //         title: "Land Registration in Ghana",
    //         category: "Lands & Properties",
    //         desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
    //         posted_by: "Ghana Lands",
    //     },
    //     {
    //         id:8,
    //         img:"assets/p8.jpg",
    //         title: "Land Registration in Ghana",
    //         category: "Lands & Properties",
    //         desc:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Faucibus non, in lorem nulla. Lectus purus faucibus euismod eu. Amet viverra nisi elit sapien non. Faucibus non, in lorem nulla. Lectus purus faucibus",
    //         posted_by: "Ghana Lands",
    //     }
]
